### ISSUE TITLE
Further specify os field

### ISSUE THREAD

**Issue by lucaswerkmeister** [nusenu/ContactInfo-Information-Sharing-Specification#1]
I think the `os` field is currently underspecified:

> String stating which OS and version is used. OS and version is separated with a "/" sign.
> 
> example: OpenBSD/6.1

For Linux distributions, is the OS “Linux” or the distribution name? And is the version the Linux kernel version or the distribution version? (In the latter case: what about rolling-release distributions like Arch?)

On Linux systems, I would suggest using the `ID` and `VERSION_ID` fields from [`/etc/os-release`](https://www.freedesktop.org/software/systemd/man/os-release.html). (Note that the `VERSION_ID` field is optional.)

I’m less familiar with *BSD, but I take it the version number is unambiguous there?

**Comment by nusenu** [comment]
Hi thank you for your input!

**Comment by lucaswerkmeister** [comment]
Wow, that was fast, thanks! :D But this doesn’t account for distributions where the `VERSION_ID` field is missing, like Arch.

**Comment by nusenu** [comment]
Thanks for that example, after I looked at debian, ubuntu, centos, fedora I assumed it is always present.
So if it is not present we can simply omit it.

**Comment by lucaswerkmeister** [comment]
Great, thanks!
