### ISSUE TITLE
For uri-rsa proof need to specify the case sensitivity for rsa-fingerprint.txt

### ISSUE THREAD

**Issue by yinanzhou** [nusenu/ContactInfo-Information-Sharing-Specification#19]
For example OrNetStats only recognize fingerprints in lowercase letters. It would be better if the specification clearifies the requirement.

**Comment by yinanzhou** [comment]
Actually seems there are both verified relays using uppercase or lowercase fingerprints. So probably some setup is wrong on my side.

**Comment by nusenu** [comment]
https://github.com/nusenu/ContactInfo-Information-Sharing-Specification#proof
-> 
https://gitlab.torproject.org/tpo/core/torspec/-/blob/main/proposals/326-tor-relay-well-known-uri-rfc8615.md#well-knowntor-relayrsa-fingerprinttxt
> Fingerprints are not case-sensitive.
