### ISSUE TITLE
Cost in other currencies

### ISSUE THREAD

**Issue by lucaswerkmeister** [nusenu/ContactInfo-Information-Sharing-Specification#2]
> Monthly hosting costs this server is causing measured in US dollar.

What if I’m not paying for the server in US dollar? Should I regularly adjust my ContactInfo for the current exchange rate?

I think it would be better to include the ISO 4217 currency code (e. g. USD, EUR) in the value, and to always specify the cost in the currency in which it’s actually paid.

**Comment by nusenu** [comment]
I actually thought about that as well.
The idea behind asking operators to convert every currency to USD is that I can simply sum up all of them without having to convert all the values first.

I agree that using the actually charged currency would be more accurate but I do not have strong expectations on how accurate the value is.

**Comment by lucaswerkmeister** [comment]
Thank you!
