### ISSUE TITLE
Decimal or binary prefixes?

### ISSUE THREAD

**Issue by lucaswerkmeister** [nusenu/ContactInfo-Information-Sharing-Specification#3]
The specification refers to SI prefixes several times (MBit/s, TB, MB). It should clarify whether those prefixes are intended as decimal or binary prefixes.

IMHO this is especially important for `memory`, because `/proc/meminfo` and `free` by default use kB (ki*bi*bytes according to **free**(1)), but the specification calls for MB, so the relay operator needs to divide by either 1000 or 1024.

**Comment by nusenu** [comment]
In practice I see the following:
- for storage: MB =  2^20  https://en.wikipedia.org/wiki/Mebibyte
- for network interface speed: 1MBit/s = 1 000 000 Bit/s

For traffic accounting I'm not entirely sure what most hosting companies actually mean when they say 50TB included. I'll try to figure out what most hosting companies mean.

**Comment by nusenu** [comment]
reference for one major provider (Tebibyte)
https://twitter.com/LucasWerkmeistr/status/920777837195472896

**Comment by nusenu** [comment]
this should be fixed with:
https://github.com/nusenu/ContactInfo-Information-Shareing-Specification/commit/71e8c271f1496255afc8ba851707eb09d731dfc6
