### ISSUE TITLE
Virtualization

### ISSUE THREAD

**Issue by lucaswerkmeister** [nusenu/ContactInfo-Information-Sharing-Specification#5]
I’m not sure whether the “virtualization” field could use some more specification, to make sure that we don’t see too many different strings used to describe the same virtualization technology in the wild.

On systems with systemd installed, the `systemd-detect-virt` tool can be used to detect the virtualization technology. As of v237, it supports the following values ([source](https://github.com/systemd/systemd/blob/b8e2400586452499131ff5ab1edb60c1dfbcf92b/src/basic/virt.c#L618-L640)):

- **kvm**
- qemu
- bochs
- **xen**
- uml
- **vmware**
- *oracle* (**virtualbox**)
- *microsoft* (**hyper-v**)
- zvm
- parallels
- **bhyve**
- vm-other
- systemd-nspawn
- lxc-libvirt
- lxc
- openvz
- docker
- rkt
- container-other

Entries which are listed in the current example values in the README are set in bold; entries which use a different string in the example values are set in italic, with the README string in bold after it. README further mentions “vmm”, which I’m not sure what to make of.

Do you think we could use that as the basis for the virtualization field?

**Comment by nusenu** [comment]
Hi Lucas,
thanks for your input.

I do not like "oracle" and "microsoft" as hypervisor names, since they are vendors not products,
what if they have more than one hypervisor..

I did not add containers (docker, ..) just yet :)

vmm is https://man.openbsd.org/vmm

**Comment by lucaswerkmeister** [comment]
Thanks for the reply! (And sorry I’m so slow with my own reply…)

Updated set of virtualization values looks good :) but perhaps the vmm link should be somehow integrated into the README as well? When I searched for the term, the only non-generic thing I found was the [Red Hat Virtual Machine Manager](https://en.wikipedia.org/wiki/Virtual_Machine_Manager).

**Comment by nusenu** [comment]
this is considered done
